# Creates a .vsix package and publishes it to GitHub artifacts
# So you can, for example, download the .vsix
# directly from a commit or a PR.
#
# May also be used by publish-openvsx.yml and publish-vscode.yml
# for auto-publishing the .vsix to the stores when a valid tag is pushed

name: Package extension to .vsix

# Run Actions when pushed to any branch, or a semver tag is created
on:
  push:
    branches:
      - "*"
    tags:
      - "*.*.*"
      - "v*"

jobs:
  package-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: Install VSCode Extension Manager
        run: npm install --global @vscode/vsce
      - name: Install dependencies
        run: npm i
      - name: Create .vsix package
        run: vsce package
      - uses: actions/upload-artifact@v3
        with:
          name: vsix-package
          path: |
            *.vsix
          if-no-files-found: error
      - name: Check if current branch is a tag
        run: git symbolic-ref HEAD
        continue-on-error: true
      - name: Set IS_GIT_TAG
        run: if [ $? -ne 0 ]; then export IS_GIT_TAG="true"; fi
      - if: env.IS_GIT_TAG == true
        uses: ./.github/workflows/publish-msmarketplace.yml
      - if: env.IS_GIT_TAG == true
        uses: ./.github/workflows/publish-openvsix.yml